<?php

declare(strict_types=1);

/**
 * Estrutura editorial do blog Vagas RJ: 11 categorias x 11 artigos (121 total).
 *
 * @return list<array{name: string, slug: string, description: string, article_titles: list<string>}>
 */
return [
    [
        'name' => 'Currículo',
        'slug' => 'curriculo',
        'description' => 'Guias práticos para montar, revisar e enviar currículo com clareza, foco em oportunidades no Rio de Janeiro.',
        'article_titles' => [
            'Como montar um currículo simples para vagas no RJ',
            'O que colocar no currículo quando não tenho experiência',
            'Erros comuns no currículo que prejudicam candidatos',
            'Como destacar cursos e certificados no currículo',
            'Como adaptar o currículo para cada vaga',
            'Como fazer um currículo para primeiro emprego',
            'Como organizar experiências profissionais antigas',
            'Como escrever objetivo profissional no currículo',
            'Como deixar o currículo mais direto e claro',
            'Como enviar currículo por e-mail corretamente',
            'Checklist antes de enviar currículo para uma vaga',
        ],
    ],
    [
        'name' => 'Entrevista de emprego',
        'slug' => 'entrevista-de-emprego',
        'description' => 'Preparação para entrevistas presenciais e online, com foco em comunicação objetiva e postura profissional.',
        'article_titles' => [
            'Como se preparar para uma entrevista de emprego',
            'Perguntas comuns em entrevistas e como responder',
            'Como falar sobre pontos fortes e fracos',
            'O que evitar em uma entrevista',
            'Como se vestir para uma entrevista',
            'Como demonstrar interesse pela vaga',
            'Como responder sobre pretensão salarial',
            'Como explicar falta de experiência',
            'Como se comportar em entrevista online',
            'Como falar sobre empregos anteriores',
            'O que fazer depois da entrevista',
        ],
    ],
    [
        'name' => 'Primeiro emprego',
        'slug' => 'primeiro-emprego',
        'description' => 'Orientações para quem busca a primeira oportunidade no mercado de trabalho fluminense.',
        'article_titles' => [
            'Como procurar o primeiro emprego no Rio de Janeiro',
            'Como conseguir vaga sem experiência',
            'O que empresas esperam de quem busca primeiro emprego',
            'Como demonstrar responsabilidade sem experiência',
            'Como organizar rotina de busca por emprego',
            'Como usar cursos gratuitos para melhorar o currículo',
            'Como procurar vagas de entrada',
            'Como se candidatar com segurança',
            'Como evitar golpes em vagas de primeiro emprego',
            'Como preparar documentos para contratação',
            'Como lidar com a primeira entrevista',
        ],
    ],
    [
        'name' => 'Mercado de trabalho no RJ',
        'slug' => 'mercado-de-trabalho-no-rj',
        'description' => 'Panorama e estratégias para buscar emprego na capital, região metropolitana e interior do estado.',
        'article_titles' => [
            'Áreas com oportunidades no Rio de Janeiro',
            'Como procurar emprego na capital e região metropolitana',
            'Diferenças entre vagas no centro e bairros do RJ',
            'Como acompanhar vagas por cidade no RJ',
            'Oportunidades em comércio e serviços no RJ',
            'Oportunidades em logística no RJ',
            'Oportunidades em atendimento no RJ',
            'Como usar portais regionais de vagas',
            'Como se organizar para processos seletivos',
            'O que observar antes de aceitar uma vaga',
            'Tendências de contratação no RJ',
        ],
    ],
    [
        'name' => 'Segurança para candidatos',
        'slug' => 'seguranca-para-candidatos',
        'description' => 'Cuidados para identificar fraudes, proteger dados e se candidatar com mais tranquilidade.',
        'article_titles' => [
            'Como identificar vaga falsa',
            'Cuidados antes de enviar documentos',
            'Por que nunca pagar para participar de processo seletivo',
            'Como confirmar se uma empresa existe',
            'Cuidados com links de candidatura',
            'Como proteger seus dados pessoais',
            'Como denunciar uma vaga suspeita',
            'Sinais de golpe em mensagens de emprego',
            'Como verificar e-mails de recrutamento',
            'Cuidados com grupos de vagas',
            'Checklist de segurança antes de se candidatar',
        ],
    ],
    [
        'name' => 'Direitos e cuidados no trabalho',
        'slug' => 'direitos-e-cuidados-no-trabalho',
        'description' => 'Informações para avaliar propostas, modalidades de contratação e documentação com responsabilidade.',
        'article_titles' => [
            'O que observar antes de aceitar uma proposta',
            'Diferença entre CLT, estágio e jovem aprendiz',
            'Cuidados com promessas de salário',
            'Como conferir informações da vaga',
            'O que perguntar antes da contratação',
            'Como guardar comprovantes de candidatura',
            'Cuidados com contratos e documentos',
            'O que verificar no primeiro dia de trabalho',
            'Como organizar informações sobre benefícios',
            'Como agir diante de uma proposta duvidosa',
            'Como buscar orientação trabalhista',
        ],
    ],
    [
        'name' => 'Carreira e desenvolvimento',
        'slug' => 'carreira-e-desenvolvimento',
        'description' => 'Hábitos e planejamento para evoluir profissionalmente de forma consistente.',
        'article_titles' => [
            'Como melhorar suas chances de contratação',
            'Como criar uma rotina de estudos para carreira',
            'Como desenvolver comunicação profissional',
            'Como melhorar postura no trabalho',
            'Como pedir feedback de forma correta',
            'Como planejar crescimento profissional',
            'Como escolher uma área para trabalhar',
            'Como aprender com processos seletivos',
            'Como se destacar em vagas concorridas',
            'Como desenvolver habilidades básicas',
            'Como manter consistência na busca por emprego',
        ],
    ],
    [
        'name' => 'Vagas por cidade',
        'slug' => 'vagas-por-cidade',
        'description' => 'Estratégias de busca por município do Rio de Janeiro, com contexto local para cada região.',
        'article_titles' => [
            'Como buscar vagas no Rio de Janeiro',
            'Como buscar vagas em Niterói',
            'Como buscar vagas em Duque de Caxias',
            'Como buscar vagas em São Gonçalo',
            'Como buscar vagas em Nova Iguaçu',
            'Como buscar vagas em Belford Roxo',
            'Como buscar vagas em Cabo Frio',
            'Como buscar vagas em Macaé',
            'Como buscar vagas em Petrópolis',
            'Como buscar vagas em Volta Redonda',
            'Como buscar vagas em Campos dos Goytacazes',
        ],
    ],
    [
        'name' => 'Profissões e áreas',
        'slug' => 'profissoes-e-areas',
        'description' => 'Caminhos para encontrar oportunidades por área de atuação no mercado carioca e fluminense.',
        'article_titles' => [
            'Como procurar vagas administrativas',
            'Como procurar vagas comerciais',
            'Como procurar vagas de logística',
            'Como procurar vagas de atendimento',
            'Como procurar vagas de tecnologia',
            'Como procurar vagas financeiras',
            'Como procurar vagas operacionais',
            'Como procurar vagas de vendas',
            'Como procurar vagas em recursos humanos',
            'Como procurar vagas em serviços gerais',
            'Como procurar vagas de auxiliar',
        ],
    ],
    [
        'name' => 'Jovem Aprendiz e estágio',
        'slug' => 'jovem-aprendiz-e-estagio',
        'description' => 'Orientações sobre programas de aprendizagem e estágio no estado do Rio de Janeiro.',
        'article_titles' => [
            'Como procurar vaga de Jovem Aprendiz no RJ',
            'Como preparar currículo para Jovem Aprendiz',
            'Como funciona uma vaga de estágio',
            'Diferença entre estágio e jovem aprendiz',
            'Como se destacar em processo de aprendizagem',
            'Documentos comuns para Jovem Aprendiz',
            'Como buscar estágio sem experiência',
            'Como se preparar para entrevista de estágio',
            'Cuidados com falsas vagas de Jovem Aprendiz',
            'Como organizar estudos e trabalho',
            'Como usar o primeiro emprego para crescer',
        ],
    ],
    [
        'name' => 'Dicas para candidatura',
        'slug' => 'dicas-para-candidatura',
        'description' => 'Boas práticas para enviar candidaturas, acompanhar processos e manter organização.',
        'article_titles' => [
            'Como se candidatar corretamente a uma vaga',
            'Como acompanhar candidaturas enviadas',
            'Como preencher formulário de emprego',
            'Como escrever mensagem para recrutador',
            'Como enviar currículo pelo WhatsApp com cuidado',
            'Como se candidatar por e-mail',
            'Como evitar erros ao preencher cadastro',
            'Como organizar links de vagas',
            'Como revisar dados antes de enviar candidatura',
            'Como responder retorno de processo seletivo',
            'Como manter uma rotina diária de candidatura',
        ],
    ],
];
